language: go

go:
  - 1.5
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./cmd/hashsrv
  - go test -v -covermode=count -coverprofile=coverage.out ./engine
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
