language: go

services:
  - docker

env:
  GO111MODULE=on

go:
  - 1.14.4

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./cmd/hashsrv
  - go test -v -covermode=count -coverprofile=coverage.out ./engine
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ancientlore/hashsrv:${TRAVIS_TAG:-latest} .
  - docker push ancientlore/hashsrv:${TRAVIS_TAG:-latest}
